project:
  type: website
  
  render:
    - index.qmd
    - about.qmd
    - Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
    - Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
    - Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.qmd
    - Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.qmd
    - Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.qmd
    - Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.qmd
    - Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.qmd
    - Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.qmd
    - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd
    - Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd
    - Hands-on_Ex/Hands-on_Ex08a/Hands-on_Ex08a.qmd
    - Hands-on_Ex/Hands-on_Ex08b/Hands-on_Ex08b.qmd
    - Hands-on_Ex/Hands-on_Ex08c/Hands-on_Ex08c.qmd
    - Hands-on_Ex/Hands-on_Ex09a/Hands-on_Ex09a.qmd
    - Hands-on_Ex/Hands-on_Ex09b/Hands-on_Ex09b.qmd
    - Hands-on_Ex/Hands-on_Ex09c/Hands-on_Ex09c.qmd    
    - Hands-on_Ex/Hands-on_Ex09d/Hands-on_Ex09d.qmd
    - Hands-on_Ex/Hands-on_Ex09e/Hands-on_Ex09e.qmd  
    - Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.qmd    
    - In-class_Ex/In-class_Ex02/In-class_Ex02.qmd
    - In-class_Ex/In-class_Ex03/In-class_Ex03.qmd
    - In-class_Ex/In-class_Ex05/In-class_Ex05.qmd
    - In-class_Ex/In-class_Ex06/In-class_Ex06.qmd
    - In-class_Ex/In-class_Ex09/In-class_Ex08.qmd
    - Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
    - Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd

  output-dir: _site #for the logo to appear

website:
  favicon: bear_heart.png
  announcement:
    content: "<i class=\"bi bi-balloon-heart-fill\"></i> **NEW! (13 JUN)** - [**Take-Home_Ex03**](https://dreytwy-th3.netlify.app/take-home_ex03) published! <br> <i class=\"bi bi-cup-hot-fill\"></i> **(13 JUN)** - Hands on [**Exercises**](https://isss608-ay2024-25-dreytwy.netlify.app/Hands-on_Ex/Hands-on_Ex08a/Hands-on_Ex08a.html) published" 
    type: warning
    position: below-navbar
  page-navigation: true
  
  navbar:
    logo: "bear_heart.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3a"
            href: "Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3b"
            href: "Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html"
          - text: "Hands-on Exercise 4a"
            href: "Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.html"
          - text: "Hands-on Exercise 4b"
            href: "Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.html"  
          - text: "Hands-on Exercise 4c"
            href: "Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.html"
          - text: "Hands-on Exercise 4d"
            href: "Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.html"             
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 8a"
            href: "Hands-on_Ex/Hands-on_Ex08a/Hands-on_Ex08a.html"
          - text: "Hands-on Exercise 8b"
            href: "Hands-on_Ex/Hands-on_Ex08b/Hands-on_Ex08b.html"
          - text: "Hands-on Exercise 8c"
            href: "Hands-on_Ex/Hands-on_Ex08c/Hands-on_Ex08c.html"             
          - text: "Hands-on Exercise 9a"
            href: "Hands-on_Ex/Hands-on_Ex09a/Hands-on_Ex09a.html"
          - text: "Hands-on Exercise 9b"
            href: "Hands-on_Ex/Hands-on_Ex09b/Hands-on_Ex09b.html"
          - text: "Hands-on Exercise 9c"
            href: "Hands-on_Ex/Hands-on_Ex09c/Hands-on_Ex09c.html"
          - text: "Hands-on Exercise 9d"
            href: "Hands-on_Ex/Hands-on_Ex09d/Hands-on_Ex09d.html"
          - text: "Hands-on Exercise 9e"
            href: "Hands-on_Ex/Hands-on_Ex09e/Hands-on_Ex09e.html"
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 2"        
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"        
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"        
          - text: "In-class Exercise 5"        
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"  
          - text: "In-class Exercise 6"        
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html" 
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take‑home Exercise 3"
            href: "https://dreytwy-th3.netlify.app/take-home_ex03"


      - text: "Project"
        menu:
          - text: "Netlify"
            href: "https://covertreef.netlify.app/"        
#          - text: "Shiny"
#            href: "Take-home_Ex03_Standalone/Take-home_Ex01/Take-home_Ex01.html"     
            
    right:
      - href: index.qmd        
        text: Home 
      - href: about.qmd
        text: About
      

format:
  html:
    favicon: bear_heart.png   # or favicon.svg or favicon.ico
    theme: pulse
    toc: true
    css: styles.css
    logo: bear_heart.png
    
      
editor: visual
