project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
    - Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
    - Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.qmd
    - Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.qmd
    - Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.qmd
    - Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.qmd
    - Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.qmd
    - Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.qmd
    - In-class_Ex/In-class_Ex02/In-class_Ex02.qmd
    - In-class_Ex/In-class_Ex03/In-class_Ex03.qmd
    - Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
  output-dir: _site #for the logo to appear

website:
  favicon: bear_heart.png
  announcement:
    content: "<i class=\"bi bi-balloon-heart-fill\"></i> **NEW! (04 MAY)** - [**Hands-on Exercise 4**](https://isss608-ay2024-25-dreytwy.netlify.app/Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.html) published! <br> <i class=\"bi bi-cup-hot-fill\"></i> **(10 MAY)** - [**Take-home Exercise 1 Part II**](https://isss608-ay2024-25-dreytwy.netlify.app/Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html) published! " 
    type: warning
    position: below-navbar
  page-navigation: true
  
  navbar:
    logo: "bear_heart.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3a"
            href: "Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3b"
            href: "Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html"
          - text: "Hands-on Exercise 4a"
            href: "Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.html"
          - text: "Hands-on Exercise 4b"
            href: "Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.html"  
          - text: "Hands-on Exercise 4c"
            href: "Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.html"
          - text: "Hands-on Exercise 4d"
            href: "Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.html"             
          # - text: "Hands-on Exercise 4"
          #   href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          # - text: "Hands-on Exercise 5"
          #   href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          # - text: "Hands-on Exercise 6"
          #   href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          # - text: "Hands-on Exercise 7"
          #   href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          # - text: "Hands-on Exercise 8"
          #   href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          # - text: "Hands-on Exercise 9"
          #   href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          # - text: "Hands-on Exercise 10"
          #   href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 2"        
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"        
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"            
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    
    right:
      - href: index.qmd        
        text: Home 
      - href: about.qmd
        text: About
      

format:
  html:
    favicon: bear_heart.png   # or favicon.svg or favicon.ico
    theme: pulse
    toc: true
    css: styles.css
    logo: bear_heart.png
      
editor: visual
