{
  "hash": "2d4c5f1f4b182f65831b55b3cb9e0e28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home_Exercise 1\"\nsubtitle: \"Demographic structures and distribution of Singapore in 2024\"\nauthor: \"Audrey Tan\"\ndate: \"03 May 2025\"\ndate-modified: \"last-modified\"\nformat: html\n\neditor: visual\nexecute: \n  eval: true\n  echo: true\n  warning: false \n  freeze: true\n---\n\n# 1. Overview\n\n## 1.1 Background and Task\n\nAero Media is a local online media company that publishes daily content on digital platforms is planning to release an article on **demographic structures and distribution of Singapore in 2024**. As a graphical editor of the media company (Aero Media), there is a need to prepare **at most** **three** non-interactive data visualisation for the daily article. This article aims to explore the distribution and structure of the population age, gender, and regions. Please refer to Section 2 to 7 for the rationalisation and preparation, and Section 8 for this Article.\n\n## 1.2 The Data\n\nTo accomplish the task, *Singapore Residents by Planning Area / Subzone, Single Year of Age and Sex, June 2024* dataset shares by [Department of Statistics, Singapore (DOS)](https://www.singstat.gov.sg/) is used.\n\n# 2. Loading Libraries and Packages\n\nThe code chunk below uses p_load() of pacman package to check if packages are installed in the computer. If they are, then they will be launched into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(ggrepel, patchwork, \n               ggthemes, hrbrthemes,\n               tidyverse, readr, ggdist, ggExtra,\n               ggridges, colorspace, knitr, plotly,\n               forcats, reshape2, png, grid, scales, cowplot,\n               dplyr, magrittr, RColorBrewer, magick, rmarkdown) \n```\n:::\n\n\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| Library               | Purpose                                                                                                                                      |\n+=======================+==============================================================================================================================================+\n| tidyverse             | -   Include dpylr for data manipulation with “mutate”, “group_by”, “summarize”, etc.                                                         |\n|                       |                                                                                                                                              |\n|                       | -   Include ggplot2 for visualisation through histogram, boxplots, etc.                                                                      |\n|                       |                                                                                                                                              |\n|                       | -   Include forcats for factoring and ordering of variables                                                                                  |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| ggdist                | For visualizing distributions and uncertainty. It provides tools like stat_halfeye(), stat_pointinterval(), etc., for making raincloud plots |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| ggExtra               | For adding functions and layers like ggMarginal() to ggplot2.                                                                                |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| ggridges              | For creating density plots for visualisation of continuous distribution                                                                      |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| ggrepel               | For repelling overlapping text labels in plot                                                                                                |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| ggthemes & hrbrthemes | For customisation of plot appearance                                                                                                         |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| patchwork             | For combination and alignment of multiple plots for each visualisation                                                                       |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| knitr                 | For elegant, flexible and fast report generation of underlying dataframes                                                                    |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| plotly                | For plotting interactive statistical graphs                                                                                                  |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| forcats               | For working with categorical variables                                                                                                       |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| reshape2              | For restructuring data between \"wide\" and \"long\" formats.                                                                                    |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| png                   | For reading and writing Portable Network Graphics (PNG) image files in R                                                                     |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| grid                  | For powerful and flexible low-level graphics system in R                                                                                     |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| dplyr                 | For data manipulation.                                                                                                                       |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| magrittr              | For introducing the pipe operator `%>%` into R.                                                                                              |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| RColorBrewer          | For creating colour palettes                                                                                                                 |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| magick                | For image processing to read, edit, compose, and convert images easily.                                                                      |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| scales                | For normalizing of a dataset using the mean value and standard deviation                                                                     |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| rmarkdown             | For converting R Markdown documents into different formats.                                                                                  |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n| cowplot               | For streamlining the process of creating and arranging plots.                                                                                |\n+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------+\n\n# 3. Importing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_demo_2024 <- read_csv(\"respopagesex2024.csv\",show_col_types = FALSE)\n```\n:::\n\n\n# 4. Data Understanding\n\n## 4.1 Viewing Data Rows and Columns using glimpse\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(sg_demo_2024)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60,424\nColumns: 6\n$ PA   <chr> \"Ang Mo Kio\", \"Ang Mo Kio\", \"Ang Mo Kio\", \"Ang Mo Kio\", \"Ang Mo K…\n$ SZ   <chr> \"Ang Mo Kio Town Centre\", \"Ang Mo Kio Town Centre\", \"Ang Mo Kio T…\n$ Age  <chr> \"0\", \"0\", \"1\", \"1\", \"2\", \"2\", \"3\", \"3\", \"4\", \"4\", \"5\", \"5\", \"6\", …\n$ Sex  <chr> \"Males\", \"Females\", \"Males\", \"Females\", \"Males\", \"Females\", \"Male…\n$ Pop  <dbl> 10, 10, 10, 10, 10, 10, 10, 10, 30, 10, 20, 10, 20, 30, 30, 10, 3…\n$ Time <dbl> 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024,…\n```\n\n\n:::\n:::\n\n\n-   The data contains data on Singapore Residents by Planning Area / Subzone, Single Year of Age and Sex, June 2024.\n-   The dataframe has 6 columns and 60,424 rows. Four of the columns contains categorical data type and the other two are in double/real number data type.\n    -   The categorical attributes are: PA, SZ, Age and Sex\n    -   The numerical attributes are: Pop, and Time.\n\n## 4.2 Data Dictionary for Variables\n\n| Category | Column Headers | Type | Description |\n|----|----|----|----|\n| Planning Area | PA | CHAR | 55 area names |\n| Subzone | SZ | CHAR | 332 area names |\n| Single Year of Age | Age | NUM | 0 to 90_and_over (in increments of 1) |\n| Sex | Sex | CHAR | Males; Females |\n| Resident Count | Pop | NUM | 0 to 1180 (in multiples of 10, with occasional breaks) |\n| Time/Period | Time | NUM | 2024 |\n\n::: callout-note\n## Note.\n\n1.  For June 2024, Planning Areas refer to areas demarcated in the Urban Redevelopment Authority's Master Plan 2019.\n2.  Data from 2003 onward exclude residents who have been away from Singapore for a continuous period of 12 months or longer as at the reference period.\n3.  The figures have been rounded to the nearest 10.\n4.  The data may not add up due to rounding.\n5.  Data was generated on 24/9/2024.\n:::\n\n### 4.2.1 Categorical values\n\nThese are the categorical values within PA and SZ.\n\n::: panel-tabset\n## The Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Unique Categories in Dataset\n\n|    |Values                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |\n|:---|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|PA  |Ang Mo Kio, Bedok, Bishan, Boon Lay, Bukit Batok, Bukit Merah, Bukit Panjang, Bukit Timah, Central Water Catchment, Changi, Changi Bay, Choa Chu Kang, Clementi, Downtown Core, Geylang, Hougang, Jurong East, Jurong West, Kallang, Lim Chu Kang, Mandai, Marina East, Marina South, Marine Parade, Museum, Newton, North-Eastern Islands, Novena, Orchard, Outram, Pasir Ris, Paya Lebar, Pioneer, Punggol, Queenstown, River Valley, Rochor, Seletar, Sembawang, Sengkang, Serangoon, Simpang, Singapore River, Southern Islands, Straits View, Sungei Kadut, Tampines, Tanglin, Tengah, Toa Payoh, Tuas, Western Islands, Western Water Catchment, Woodlands, Yishun                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |\n|SZ  |Ang Mo Kio Town Centre, Cheng San, Chong Boon, Kebun Bahru, Sembawang Hills, Shangri-La, Tagore, Townsville, Yio Chu Kang, Yio Chu Kang East, Yio Chu Kang North, Yio Chu Kang West, Bayshore, Bedok North, Bedok Reservoir, Bedok South, Frankel, Kaki Bukit, Kembangan, Siglap, Bishan East, Marymount, Upper Thomson, Liu Fang, Samulun, Shipyard, Tukang, Brickworks, Bukit Batok Central, Bukit Batok East, Bukit Batok South, Bukit Batok West, Gombak, Guilin, Hillview, Hong Kah North, Alexandra Hill, Alexandra North, Bukit Ho Swee, Bukit Merah, City Terminals, Depot Road, Everton Park, Henderson Hill, Kampong Tiong Bahru, Maritime Square, Redhill, Singapore General Hospital, Telok Blangah Drive, Telok Blangah Rise, Telok Blangah Way, Tiong Bahru, Tiong Bahru Station, Bangkit, Dairy Farm, Fajar, Jelebu, Nature Reserve, Saujana, Senja, Anak Bukit, Coronation Road, Farrer Court, Hillcrest, Holland Road, Leedon Park, Swiss Club, Ulu Pandan, Central Water Catchment, Changi Airport, Changi Point, Changi West, Changi Bay, Choa Chu Kang Central, Choa Chu Kang North, Keat Hong, Peng Siang, Teck Whye, Yew Tee, Clementi Central, Clementi North, Clementi West, Clementi Woods, Faber, Pandan, Sunset Way, Toh Tuck, West Coast, Anson, Bayfront Subzone, Bugis, Cecil, Central Subzone, City Hall, Clifford Pier, Marina Centre, Maxwell, Nicoll, Phillip, Raffles Place, Tanjong Pagar, Aljunied, Geylang East, Kallang Way, Kampong Ubi, Macpherson, Defu Industrial Park, Hougang Central, Hougang East, Hougang West, Kangkar, Kovan, Lorong Ah Soo, Lorong Halus, Tai Seng, Trafalgar, International Business Park, Jurong Gateway, Jurong Port, Jurong River, Lakeside (Business), Lakeside (Leisure), Penjuru Crescent, Teban Gardens, Toh Guan, Yuhua East, Yuhua West, Boon Lay Place, Chin Bee, Hong Kah, Jurong West Central, Kian Teck, Safti, Taman Jurong, Wenya, Yunnan, Bendemeer, Boon Keng, Crawford, Geylang Bahru, Kallang Bahru, Kampong Bugis, Kampong Java, Lavender, Tanjong Rhu, Lim Chu Kang, Mandai East, Mandai Estate, Mandai West, Marina East, Marina South, East Coast, Katong, Marina East (Mp), Marine Parade, Mountbatten, Bras Basah, Dhoby Ghaut, Fort Canning, Cairnhill, Goodwood Park, Istana Negara, Monk's Hill, Newton Circus, Orange Grove, North-Eastern Islands, Balestier, Dunearn, Malcolm, Moulmein, Mount Pleasant, Boulevard, Somerset, Tanglin, China Square, Chinatown, Pearl's Hill, People's Park, Flora Drive, Loyang East, Loyang West, Pasir Ris Central, Pasir Ris Drive, Pasir Ris Park, Pasir Ris Wafer Fab Park, Pasir Ris West, Airport Road, Paya Lebar East, Paya Lebar North, Paya Lebar West, Plab, Benoi Sector, Gul Basin, Gul Circle, Joo Koon, Pioneer Sector, Coney Island, Matilda, Northshore, Punggol Canal, Punggol Field, Punggol Town Centre, Waterway East, Commonwealth, Dover, Ghim Moh, Holland Drive, Kent Ridge, Margaret Drive, Mei Chin, National University Of S'pore, One North, Pasir Panjang 1, Pasir Panjang 2, Port, Queensway, Singapore Polytechnic, Tanglin Halt, Institution Hill, Leonie Hill, One Tree Hill, Oxley, Paterson, Bencoolen, Farrer Park, Kampong Glam, Little India, Mackenzie, Mount Emily, Rochor Canal, Selegie, Sungei Road, Victoria, Pulau Punggol Barat, Pulau Punggol Timor, Seletar, Seletar Aerospace Park, Admiralty, Sembawang Central, Sembawang East, Sembawang North, Sembawang Springs, Sembawang Straits, Senoko North, Senoko South, The Wharves, Anchorvale, Compassvale, Fernvale, Lorong Halus North, Rivervale, Sengkang Town Centre, Sengkang West, Lorong Chuan, Seletar Hills, Serangoon Central, Serangoon Garden, Serangoon North, Serangoon North Ind Estate, Upper Paya Lebar, Pulau Seletar, Simpang North, Simpang South, Tanjong Irau, Boat Quay, Clarke Quay, Robertson Quay, Sentosa, Southern Group, Straits View, Gali Batu, Kranji, Pang Sua, Reservoir View, Turf Club, Simei, Tampines East, Tampines North, Tampines West, Xilin, Chatsworth, Nassim, Ridout, Tyersall, Brickland, Forest Hill, Garden, Park, Plantation, Tengah Industrial Estate, Bidadari, Boon Teck, Braddell, Joo Seng, Kim Keat, Lorong 8 Toa Payoh, Pei Chun, Potong Pasir, Sennett, Toa Payoh Central, Toa Payoh West, Woodleigh, Tengeh, Tuas Bay, Tuas North, Tuas Promenade, Tuas View, Tuas View Extension, Jurong Island And Bukom, Semakau, Sudong, Bahar, Cleantech, Murai, Greenwood Park, Midview, North Coast, Senoko West, Woodgrove, Woodlands East, Woodlands Regional Centre, Woodlands South, Woodlands West, Khatib, Lower Seletar, Nee Soon, Northland, Springleaf, Yishun Central, Yishun East, Yishun South, Yishun West |\n|Age |0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90_and_Over                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |\n|Sex |Males, Females                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |\n\n\n:::\n:::\n\n\n## The Code\n\n``` r\n# Understanding the unique data values in each column that is categorical.\n\nget_unique_val <- function(df){lapply(df, unique)}\nsg_demo_2024_cat <- sg_demo_2024[,c(\"PA\", \"SZ\", \"Age\", \"Sex\")]\nunique_val <- get_unique_val(sg_demo_2024_cat)\nuni_val_df <- data.frame(\n  Values = sapply(unique_val, paste, collapse = \", \")\n)\n\nkable(uni_val_df, caption = \"Unique Categories in Dataset\", row.names = NA, label = NULL)\n```\n:::\n\n### 4.2.2 Statistics of Numerical Variables\n\nNotice that:\n\n-   Age variable is not a numerical value but a categorical value.\n\n-   The statistics for Pop variable are not very useful as the values are a summation for each combination of variables in a particular record.\n\n-   In Time variable, there is only one year of data at 2024.\n\n::: panel-tabset\n## The Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|   |     Pop       |     Time    |\n|:--|:--------------|:------------|\n|   |Min.   :   0.0 |Min.   :2024 |\n|   |1st Qu.:   0.0 |1st Qu.:2024 |\n|   |Median :  20.0 |Median :2024 |\n|   |Mean   :  69.4 |Mean   :2024 |\n|   |3rd Qu.:  90.0 |3rd Qu.:2024 |\n|   |Max.   :1180.0 |Max.   :2024 |\n\n\n:::\n:::\n\n\n## The Code\n\n``` r\n# Understanding the distribution of numerical values \nrealis_num <- sg_demo_2024[,c(\"Pop\", \"Time\")]\n  \nkable(summary(realis_num))\n```\n:::\n\n## 4.3 Flowchart of data and graphs\n\nThe flowchart displays the course of action to be undertaken to pre-process the data to produce the eventual graphs.\n\n-   Starts from the data in cylindrical shape.\n\n-   Categorical variables are in rounded edge rectangles.\n\n-   Numerical variables are circles.\n\n-   Discretized data are in hexagons.\n\n-   Graphs are in a subroutine shape.\n\n::: panel-tabset\n## The Flowchart\n\n```{mermaid}\n%%| echo: false\n\n%%{\n  init: {\n    'theme': 'base',\n    'themeVariables': {\n    }\n  }\n}%%\n\nflowchart TD\n    id1[(sg_demo_2024)]-->C((Pop))\n    C((Pop))-->G(Sub_Zone)\n    G(Sub_Zone)--> F(Planning_Area) \n\n    F -->|Discretize| id2{{Region Type - CR, ER, NR, NER, WR}}\n    id2 -->|Filter| D(Sex)\n    D(Sex)--> |Filter| B(Age)\n    D(Sex)-->|Graph Type|K[[❤ EDA 2: Pyramid Bar]] \n\n    D(Sex)--> |Graph Type|N[[Stacked Bar Chart]]\n\n    B(Age) -->|Change Type| H((Age_Numerical))\n    B(Age) -->|Discretize| id3{{summarised_ages - young, working-age, elderly}}\n    B(Age) -->|Discretize| id4{{Age_type - 0-4,5-9,...,90 & Over}}\n\n    id3--> |Graph Type|M[[Bar Chart]]\n    id4--> |Graph Type|A[[❤ EDA 1: Population Pyramids]]\n   \n    H((Age_Numerical))-->|Graph Type|O[[Histogram]] \n \n\n```\n\n## The Code\n\n\n::: {.cell}\n\n```{.markdown .cell-code}\n\n%%{\n  init: {\n    'theme': 'base',\n    'themeVariables': {\n    }\n  }\n}%%\n\nflowchart TD\n    id1[(sg_demo_2024)]-->C((Pop))\n    C((Pop))-->G(Sub_Zone)\n    G(Sub_Zone)--> F(Planning_Area) \n\n    F -->|Discretize| id2{{Region Type - CR, ER, NR, NER, WR}}\n    id2 -->|Filter| D(Sex)\n    D(Sex)--> |Filter| B(Age)\n    D(Sex)-->|Graph Type|K[[❤ EDA 2: Pyramid Bar]] \n\n    D(Sex)--> |Graph Type|L[[Pie Chart]]\n    D(Sex)--> |Graph Type|N[[Stacked Bar Chart]]\n\n    B(Age) -->|Change Type| H((Age_Numerical))\n    B(Age) -->|Discretize| id3{{summarised_ages - young, working-age, elderly}}\n    B(Age) -->|Discretize| id4{{Age_type - 0-4,5-9,...,90 & Over}}\n\n    id3--> |Graph Type|M[[Bar Chart]]\n    id4--> |Graph Type|A[[❤ EDA 1: Population Pyramids]]\n   \n    H((Age_Numerical))-->|Graph Type|O[[Histogram]] \n```\n:::\n\n:::\n\n# 5. Data Pre-processing\n\nThere are 4 major tasks in data pre-processing: Data cleaning, Data Integration, Data Reduction, and Data Transformation. Here we focus on data cleaning, transformation and reduction.\n\n## 5.1 Data Cleaning\n\nVerifying data quality through checking for missing values and duplicates.\n\n### 5.1.1 Missing Values\n\n::: panel-tabset\n## The Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 6\n# ℹ 6 variables: PA <chr>, SZ <chr>, Age <chr>, Sex <chr>, Pop <dbl>,\n#   Time <dbl>\n```\n\n\n:::\n:::\n\n\n## The Code\n\n``` r\nsg_demo_2024[missing(sg_demo_2024),]\n```\n:::\n\n### 5.1.2 Duplicates\n\n::: panel-tabset\n## The Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 6\n# ℹ 6 variables: PA <chr>, SZ <chr>, Age <chr>, Sex <chr>, Pop <dbl>,\n#   Time <dbl>\n```\n\n\n:::\n:::\n\n\n## The Code\n\n``` r\nsg_demo_2024[duplicated(sg_demo_2024),]\n```\n:::\n\nThere were no missing values or duplicates.\n\n## 5.2 Data Transformation/ Reduction\n\n### 5.2.1 Data Label Encoding: Changing Age from categorical to numerical type\n\nAge as a continuous variable will be useful for plotting distributions.\n\n::: panel-tabset\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_demo_2024 <- sg_demo_2024 %>%\n  mutate(Age_numerical_temp = ifelse(Age == \"90_and_Over\", \"90\", Age)) %>%\n  mutate(Age_numerical = as.numeric(Age_numerical_temp)) %>%\n  select(-Age_numerical_temp) # remove the temporary column\n```\n:::\n\n:::\n\n### 5.2.2 Discretization: Creation of new Region_type\n\nThe discretization method splits the continuous data into intervals which reduces the data size and for ease of visualising through smaller segments. There are 55 planning area (PA) and 332 subzone (SZ), referencing Urban Redevelopment Authority (URA), the PA or SZ can be grouped into 5 regions:\n\n-   Central Region (CR)\n\n-   East Region (ER)\n\n-   North Region (NR)\n\n-   North East Region (NER)\n\n-   West Region (WR)\n\nHence, a new column of Region_type was created to reflect the 5 segmented regions using PA.\n\n::: panel-tabset\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Encoding regions\nsg_demo_2024 <- sg_demo_2024 %>% \n  mutate(Region_type = case_when(\n    `PA` %in% c(\"Bishan\", \"Bukit Merah\", \"Bukit Timah\", \"Downtown Core\", \"Geylang\",\n                \"Kallang\",\"Marina East\",\"Marina South\", \"Marine Parade\", \"Museum\",\n                \"Newton\", \"Novena\", \"Orchard\",\"Outram\",\"Queenstown\",\"River Valley\",\n                \"Rochor\",\"Singapore River\",\"Southern Islands\", \"Straits View\",\n                \"Tanglin\",\"Toa Payoh\") ~ \"CR\",\n    `PA` %in% c(\"Bedok\",\"Changi\",\"Changi Bay\",\"Pasir Ris\",\"Paya Lebar\",\"Tampines\") ~ \"ER\",\n    `PA` %in% c(\"Central Water Catchment\",\"Lim Chu Kang\",\"Mandai\",\n                \"Sembawang\", \"Simpang\", \"Sungei Kadut\",\"Woodlands\",\"Yishun\") ~ \"NR\",\n    `PA` %in% c(\"Ang Mo Kio\",\"Hougang\", \"North-Eastern Islands\", \"Punggol\", \n                \"Seletar\", \"Sengkang\", \"Serangoon\") ~ \"NER\",\n    `PA` %in% c(\"Boon Lay\", \"Bukit Batok\", \"Bukit Panjang\", \"Choa Chu Kang\",\n                \"Clementi\", \"Jurong East\", \"Jurong West\", \"Pioneer\", \"Tengah\",\n                \"Tuas\", \"Western Islands\",\"Western Water Catchment\") ~ \"WR\"\n  ))\n```\n:::\n\n:::\n\nThese are the summarised data.\n\n::: panel-tabset\n## The Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Region_type |Planning_Area                                                                                                                                                                                                                                               |\n|:-----------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|CR          |Bishan, Bukit Merah, Bukit Timah, Downtown Core, Geylang, Kallang, Marina East, Marina South, Marine Parade, Museum, Newton, Novena, Orchard, Outram, Queenstown, River Valley, Rochor, Singapore River, Southern Islands, Straits View, Tanglin, Toa Payoh |\n|ER          |Bedok, Changi, Changi Bay, Pasir Ris, Paya Lebar, Tampines                                                                                                                                                                                                  |\n|NER         |Ang Mo Kio, Hougang, North-Eastern Islands, Punggol, Seletar, Sengkang, Serangoon                                                                                                                                                                           |\n|NR          |Central Water Catchment, Lim Chu Kang, Mandai, Sembawang, Simpang, Sungei Kadut, Woodlands, Yishun                                                                                                                                                          |\n|WR          |Boon Lay, Bukit Batok, Bukit Panjang, Choa Chu Kang, Clementi, Jurong East, Jurong West, Pioneer, Tengah, Tuas, Western Islands, Western Water Catchment                                                                                                    |\n\n\n:::\n:::\n\n\n## The Code\n\n``` r\npa_mapping<- sg_demo_2024 %>%\n  group_by(`Region_type`) %>%\n  summarize(Planning_Area = paste(unique(`PA`), collapse = \", \"))\n\nkable(pa_mapping, title = \"Mapping of Planning Area to Region \")\n```\n:::\n\n### 5.2.3 Discretization: Creation of new Age_Type\n\nThe ages were binned into Age_type based on Singapore's Department of Statistics classification.\n\n::: panel-tabset\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Encoding ages\nsg_demo_2024 <- sg_demo_2024 %>% \n  mutate(Age_type = case_when(\n    Age %in% as.character(0:4) ~ \"0-4\",\n    Age %in% as.character(5:9) ~ \"5-9\",\n    Age %in% as.character(10:14) ~ \"10-14\",\n    Age %in% as.character(15:19) ~ \"15-19\",\n    Age %in% as.character(20:24) ~ \"20-24\",\n    Age %in% as.character(25:29) ~ \"25-29\",\n    Age %in% as.character(30:34) ~ \"30-34\",\n    Age %in% as.character(35:39) ~ \"35-39\",\n    Age %in% as.character(40:44) ~ \"40-44\",\n    Age %in% as.character(45:49) ~ \"45-49\",\n    Age %in% as.character(50:54) ~ \"50-54\",\n    Age %in% as.character(55:59) ~ \"55-59\",\n    Age %in% as.character(60:64) ~ \"60-64\",\n    Age %in% as.character(65:69) ~ \"65-69\",\n    Age %in% as.character(70:74) ~ \"70-74\",\n    Age %in% as.character(75:79) ~ \"75-79\",\n    Age %in% as.character(80:84) ~ \"80-84\",\n    Age %in% as.character(85:89) ~ \"85-89\",\n    Age == \"90_and_Over\" ~ \"90 & Over\",\n    TRUE ~ NA_character_\n  ))\n```\n:::\n\n:::\n\n### 5.2.4 Discretization: Creation of new summarised_ages\n\nBased on Singapore Department of Statistics's classification, elderly are persons aged 65 and older. Based on the Ministry of Manpower the working-age population comprises of persons aged 15 and over. Thus, the remaining younger population are classified as young here.\n\n::: panel-tabset\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Encoding summarised_ages\nsg_demo_2024 <- sg_demo_2024 %>% \n  mutate(summarised_ages = case_when(\n    Age %in% as.character(0:14) ~ \"young\",\n    Age %in% as.character(15:64) ~ \"working-age\",\n    Age %in% as.character(65:89) ~ \"eldery\",\n    Age == \"90_and_Over\" ~ \"eldery\",\n    TRUE ~ NA_character_\n  ))\n```\n:::\n\n:::\n\n### 5.2.5 Discretization: Creation of new pop_by_gender_age dataframe and new total_pop variable\n\nThere is no need to keep Time, PA, SZ, and Age variables. This helps in data or dimension reduction and reduces computation power.\n\n::: panel-tabset\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using groupby() and summarise \npop_by_gender_age<- sg_demo_2024 %>%\n  group_by(Sex, Age_numerical, Age_type, Region_type)%>%\n  summarize(total_pop = sum(Pop), .groups = \"drop\")\n```\n:::\n\n:::\n\n## 5.3 Preview of reduced dataframe\n\nDataframes *pop_by_gender_age* and the original *sg_demo_2024* were used to plot graphs in Section 7 and 8.\n\n### 5.3.1 Composition of *pop_by_gender_age* dataframe\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(pop_by_gender_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 910\nColumns: 5\n$ Sex           <chr> \"Females\", \"Females\", \"Females\", \"Females\", \"Females\", \"…\n$ Age_numerical <dbl> 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3,…\n$ Age_type      <chr> \"0-4\", \"0-4\", \"0-4\", \"0-4\", \"0-4\", \"0-4\", \"0-4\", \"0-4\", …\n$ Region_type   <chr> \"CR\", \"ER\", \"NER\", \"NR\", \"WR\", \"CR\", \"ER\", \"NER\", \"NR\", …\n$ total_pop     <dbl> 3040, 2400, 3520, 2260, 3150, 3430, 2650, 3780, 2350, 33…\n```\n\n\n:::\n:::\n\n\n-   The dataframe has 5 columns and 910 rows. Three of the columns contains categorical data type and the other two are in double/real number data type.\n-   The categorical attributes are: Region_type, Age_type, and Sex\n-   The numerical attributes are: Age_numerical, and total_pop.\n\n### 5.3.2 Understanding the distribution of numerical values\n\nThe median age here is computed by it's Age_numerical column and is not a representation of the entire population.\n\n::: panel-tabset\n## The Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|   |Age_numerical |  total_pop  |\n|:--|:-------------|:------------|\n|   |Min.   : 0    |Min.   : 220 |\n|   |1st Qu.:22    |1st Qu.:3340 |\n|   |Median :45    |Median :4625 |\n|   |Mean   :45    |Mean   :4608 |\n|   |3rd Qu.:68    |3rd Qu.:6190 |\n|   |Max.   :90    |Max.   :9100 |\n\n\n:::\n:::\n\n\n## The Code\n\n``` r\nrealis_num2 <- pop_by_gender_age[,c(\"Age_numerical\", \"total_pop\")]\n  \nkable(summary(realis_num2))\n```\n:::\n\n# 6. Univariate/ Bivariate Analysis\n\nHere, we produce some univariate and bivariate analysis to obtain a general understanding of the data and also compare between and choose visualisations.\n\n## 6.1 Bar Chart of Region by Different Population Age Groups\n\nThe bar chart hows the percentage and absolute figures of the different age group of residents by region\n\n::: panel-tabset\n## The Code for Bar Chart on Percentage Figures\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using groupby() and summarise \npop_by_region<- sg_demo_2024 %>%\n  group_by(summarised_ages, Region_type) %>%\n  summarize(pop_region = sum(Pop), .groups = \"drop\")\n\n# Calculate percentages by summarised_ages\npop_by_region_percent <- pop_by_region %>%\n  group_by(summarised_ages) %>%\n  mutate(percent = pop_region / sum(pop_region)) %>%\n  ungroup()\n\np1 <- ggplot(pop_by_region_percent,\n             aes(x = reorder(Region_type, -pop_region), y = percent,\n                 fill = summarised_ages, # Keep fill for visual distinction\n                 text = paste(\"Age Group:\", summarised_ages, \"<br>\",\n                              \"Region:\", Region_type, \"<br>\",\n                              \"Percent:\", scales::percent(percent, accuracy = 0.1), \"<br>\",\n                              \"Population:\", scales::comma(pop_region)))) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  theme(plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"),\n        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),\n        axis.title.x = element_text(vjust = -1),\n        strip.text = element_text(size = 10),\n        panel.spacing.x = unit(1, \"lines\"),\n        legend.position = \"none\") + \n  labs(x = \"Region\",\n       y = \"Percent per age-group\",\n       title  = \"Population by Age-groups and Regions (Percentage)\") +\n  scale_y_continuous(labels = scales::percent) +\n  facet_wrap(vars(summarised_ages), nrow = 1, scales = \"free_x\") +\n  scale_fill_brewer(palette = \"Set3\") # Use a color palette for regions\n\n# Create an interactive plotly object with hover\nlibrary(plotly)\nggplotly(p1, tooltip = \"text\") %>%\n  style(hoverlabel = list(bgcolor = \"blue\"))\n```\n:::\n\n\n## The Code for Bar Chart on Absolute Figures\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_by_region <- sg_demo_2024 %>%\n  group_by(summarised_ages, Region_type) %>%\n  summarize(pop_region = sum(Pop), .groups = \"drop\")\n\n# Plot the absolute population figures\np2 <- ggplot(pop_by_region,\n             aes(x = reorder(Region_type, -pop_region), y = pop_region,\n                 fill = summarised_ages, # Fill by region for distinction\n                 text = paste(\"Age Group:\", summarised_ages, \"<br>\",\n                              \"Region:\", Region_type, \"<br>\",\n                              \"Population:\", scales::comma(pop_region)))) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  theme(plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"),\n        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10),\n        axis.title.x = element_text(vjust = -1),\n        strip.text = element_text(size = 10),\n        panel.spacing.x = unit(1, \"lines\"),\n        legend.position = \"none\") +\n  labs(x = \"Region\",\n       y = \"Population\",\n       title  = \"Population by Age-groups and Regions (Absolute Figures)\",\n       fill = \"Region\") + # Update legend title\n  scale_y_continuous(labels = scales::comma) +\n  facet_wrap(vars(summarised_ages), nrow = 1, scales = \"free_x\") +\n  scale_fill_brewer(palette = \"Set3\") # Use a color palette for regions\n\n# Create an interactive plotly object with hover\nggplotly(p2, tooltip = \"text\") %>%\n  style(hoverlabel = list(bgcolor = \"blue\"))\n```\n:::\n\n\n## The Combined Bar Charts\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1/p2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n:::\n\n-   There are less residents in the East and North regions, relative to other other regions.\n\n-   Most of the population are in the working-age group due to the larger age range (15-64).\n\n-   Among the elderly population, there are significantly more elderly in the central region, compared to other regions. There are less elderly in the northern region, relative to other regions.\n\n-   Among the younger population, there is a younger population in the north eastern region relative to other regions.\n\n-   The population in the working age group are close to evenly distributed in the 3 regions of North-Eastern, Central and Western Regions of Singapore.\n\n### 6.2 Stacked Bar chart of Region by Population (with gender as hue)\n\n::: panel-tabset\n## The Stacked Bar Chart\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-5b7f6a3baf7cfe072b41\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5b7f6a3baf7cfe072b41\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.90000000000000013,0.90000000000000036,0.89999999999999991,0.90000000000000036,0.90000000000000036],\"base\":[0.11054886932965784,0.082374515026719733,0.11269026333423154,0.070708925416057597,0.11049402293533134],\"x\":[2,4,1,5,3],\"y\":[0.12065968289245575,0.08691484262661768,0.11934575405446007,0.072185008811192483,0.11407811557327596],\"text\":[\"Population: 505990 <br />Percent (%): 12.07 <br />Gender: Females\",\"Population: 364480 <br />Percent (%): 8.69 <br />Gender: Females\",\"Population: 500480 <br />Percent (%): 11.93 <br />Gender: Females\",\"Population: 302710 <br />Percent (%): 7.22 <br />Gender: Females\",\"Population: 478390 <br />Percent (%): 11.41 <br />Gender: Females\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"}},\"name\":\"Females\",\"legendgroup\":\"Females\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"hoverlabel\":{\"bgcolor\":\"blue\"}},{\"orientation\":\"v\",\"width\":[0.90000000000000013,0.90000000000000036,0.89999999999999991,0.90000000000000036,0.90000000000000036],\"base\":[0,0,0,0,0],\"x\":[2,4,1,5,3],\"y\":[0.11054886932965784,0.082374515026719733,0.11269026333423154,0.070708925416057597,0.11049402293533134],\"text\":[\"Population: 463590 <br />Percent (%): 11.05 <br />Gender: Males\",\"Population: 345440 <br />Percent (%): 8.24 <br />Gender: Males\",\"Population: 472570 <br />Percent (%): 11.27 <br />Gender: Males\",\"Population: 296520 <br />Percent (%): 7.07 <br />Gender: Males\",\"Population: 463360 <br />Percent (%): 11.05 <br />Gender: Males\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"}},\"name\":\"Males\",\"legendgroup\":\"Males\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null,\"hoverlabel\":{\"bgcolor\":\"blue\"}}],\"layout\":{\"margin\":{\"t\":47.481942714819425,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"<b> Population of Residents by Region <\\/b>\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":21.253632212536321},\"x\":0.5,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,5.5999999999999996],\"tickmode\":\"array\",\"ticktext\":[\"NER\",\"CR\",\"WR\",\"ER\",\"NR\"],\"tickvals\":[1,2,3,4,5],\"categoryorder\":\"array\",\"categoryarray\":[\"NER\",\"CR\",\"WR\",\"ER\",\"NR\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Region\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.011601800869434582,0.24363781825812619],\"tickmode\":\"array\",\"ticktext\":[\"0%\",\"5%\",\"10%\",\"15%\",\"20%\"],\"tickvals\":[0,0.050000000000000003,0.10000000000000001,0.14999999999999999,0.20000000000000001],\"categoryorder\":\"array\",\"categoryarray\":[\"0%\",\"5%\",\"10%\",\"15%\",\"20%\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Percent\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Sex\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"155840f45417\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"155840f45417\",\"visdat\":{\"155840f45417\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## The Code for Stacked bar chart\n\n``` r\n# Using groupby() and summarise \npop_by_region<- sg_demo_2024 %>%\n  group_by(Region_type,Sex) %>%\n  summarize(pop_region = sum(Pop), .groups = \"drop\")\n\n# plot the distribution as percentages\np4<-ggplot(pop_by_region, \n       aes(x = reorder(Region_type, -pop_region), y = pop_region/sum(pop_region),\n           fill=Sex,\n           text = paste(\"Population:\", pop_region,\n                        \"\\nPercent (%):\", round(100 *pop_region / sum(pop_region), digits = 2),\n                        \"\\nGender:\", Sex)))+ \n  geom_bar(stat = \"identity\", color = \"black\") +    \n  theme(plot.title = element_text(hjust = 0.5, size = 16, face = \"bold\")) + \n  labs(x = \"Region\", \n       y = \"Percent\", \n       title  = \"Population of Residents by Region\") +\n  scale_y_continuous(labels = scales::percent)\nggplotly(p4, tooltip = \"text\")%>%\n  style(\n    hoverlabel = list(bgcolor = \"blue\")\n  )\n```\n:::\n\n-   There is a rather even distribution of gender in each region.\n\n-   ER and NR have lesser population compared to the other regions, as confirmed in section 6.1.\n\n# 7. Rationalisation and Processing of Exploratory Data Analysis (EDA) before Publishing\n\nHere, the graphical editor visualises, finds insights, plans, and rationalises the appropriate chart for the article in Section 8.\n\n## 7.1 Population Pyramid\n\nInstead of the histogram produced in the earlier univariate/ bivariate analysis, a population pyramid can be produced for clearer visualisation of **Age and Gender Structure.**\n\n#### Step 1: Preparatory work\n\n::: panel-tabset\n## The Code to create pyramid\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_by_gender_age <-\n  pop_by_gender_age |>\n  mutate(total_pop = if_else(Sex == \"Males\", total_pop, -total_pop))\n```\n:::\n\n\n## The Code to calculate Total Population and Median Age\n\nCheck the total population and median ages:\n\n-   The total population is around 4,193,530.\n\n-   The median age of the population is around 42 years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ensure total_pop is positive for this calculation\npop_for_median <- pop_by_gender_age %>%\n  mutate(abs_total_pop = abs(total_pop))\n\n# Calculate the cumulative population\npop_cumulative <- pop_for_median %>%\n  arrange(Age_numerical) %>%\n  mutate(cumulative_pop = cumsum(abs_total_pop))\n\n# Find the total population\ntotal_population <- sum(pop_cumulative$abs_total_pop)\nprint(paste(\"Total Population:\", total_population))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Total Population: 4193530\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Determine the median population (half of the total)\nmedian_population_point <- total_population / 2\n\n# Find the age at which the cumulative population crosses the median point\nmedian_age_population <- pop_cumulative %>%\n  filter(cumulative_pop >= median_population_point) %>%\n  slice_head(n = 1) %>%\n  pull(Age_numerical)\n\nprint(paste(\"Median Age of the Population:\", median_age_population))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Median Age of the Population: 42\"\n```\n\n\n:::\n:::\n\n\n## The Code to create Age labels and its plot\n\nAge labels were created for ordered age.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creation of age labels\nage_labels <-\n  tibble(\n    Age_type = c(\n      \"0-4\",\n      \"5-9\",\n      \"10-14\",\n      \"15-19\",\n      \"20-24\",\n      \"25-29\",\n      \"30-34\",\n      \"35-39\",\n      \"40-44\",\n      \"45-49\",\n      \"50-54\",\n      \"55-59\",\n      \"60-64\",\n      \"65-69\",\n      \"70-74\",\n      \"75-79\",\n      \"80-84\",\n      \"85-89\",\n      \"90 & Over\"\n    )\n  ) |>\n  mutate(\n    Age_type = fct_inorder(Age_type)\n  )\n\n# age_labels plot only\nage_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text() +\n  theme_void()+\n  ggtitle(\"Age Group\\n(Years)\")+\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size=10,\n                                  face = \"bold\", color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n## The Code to create of new column Age_Type_Ordered\n\nTo ensure that the Age_type column in pop_by_gender_age is a factor with the levels taken directly from age_labels\\$Age_type, new column Age_Type_Ordered is created.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creation of ordered factor\npop_by_gender_age <- pop_by_gender_age %>%\n  mutate(Age_Type_Ordered = factor(Age_type, levels = age_labels$Age_type))\nprint(levels(pop_by_gender_age$Age_Type_Ordered))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"0-4\"       \"5-9\"       \"10-14\"     \"15-19\"     \"20-24\"     \"25-29\"    \n [7] \"30-34\"     \"35-39\"     \"40-44\"     \"45-49\"     \"50-54\"     \"55-59\"    \n[13] \"60-64\"     \"65-69\"     \"70-74\"     \"75-79\"     \"80-84\"     \"85-89\"    \n[19] \"90 & Over\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Double checking factor for Age_type matches for pop_by_gender_age and age_labels\nunique_pop_age <- unique(pop_by_gender_age$Age_type)\nprint(\"Unique values in pop_by_gender_age$Age_type:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Unique values in pop_by_gender_age$Age_type:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(unique_pop_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"0-4\"       \"5-9\"       \"10-14\"     \"15-19\"     \"20-24\"     \"25-29\"    \n [7] \"30-34\"     \"35-39\"     \"40-44\"     \"45-49\"     \"50-54\"     \"55-59\"    \n[13] \"60-64\"     \"65-69\"     \"70-74\"     \"75-79\"     \"80-84\"     \"85-89\"    \n[19] \"90 & Over\"\n```\n\n\n:::\n\n```{.r .cell-code}\nunique_labels_age <- unique(age_labels$Age_type)\nprint(\"Unique values in age_labels$Age_type:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Unique values in age_labels$Age_type:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(unique_labels_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0-4       5-9       10-14     15-19     20-24     25-29     30-34    \n [8] 35-39     40-44     45-49     50-54     55-59     60-64     65-69    \n[15] 70-74     75-79     80-84     85-89     90 & Over\n19 Levels: 0-4 5-9 10-14 15-19 20-24 25-29 30-34 35-39 40-44 45-49 ... 90 & Over\n```\n\n\n:::\n:::\n\n:::\n\n#### Step 2: Plotting of Male + Female + Age Label plots\n\n::: panel-tabset\n## Plot of Females and Males\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Code of the plot of Females and Males\n\n``` r\n\n#one women plot\npopulation_pyramid_women <-\n  pop_by_gender_age |>\n  filter(Sex == \"Females\") |>\n  ggplot(aes(\n    x = total_pop,\n    y = Age_Type_Ordered  \n  )) +\n    geom_col(fill = \"#F8766D\",alpha = 0.8) +\n  annotate(\n  geom = \"label\",\n  x = -120000,\n  y = 19,\n  label = \"Females\",\n  fill = \"#F8766D\",\n  alpha = 0.8,\n  color = \"black\",\n  label.size = 0,\n  label.padding = unit(0.3, \"lines\")\n)+\n  scale_x_continuous(breaks = breaks_pretty(), \n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"))+\n  theme_void()+\n  theme(\n    axis.text.x = element_text(),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\n\n# one men plot\npopulation_pyramid_men <-\n  pop_by_gender_age |>\n  filter(Sex == \"Males\") |>\n  ggplot(aes(\n    x = total_pop,\n    y = Age_Type_Ordered \n  )) +\n  geom_col(fill = \"#00BFC4\",alpha = 0.8)+\n  annotate(\n  geom = \"label\",\n  x = 120000,\n  y = 19,\n  label = \"Males\",\n  fill = \"#00BFC4\",\n  alpha = 0.8,\n  color = \"black\",\n  label.size = 0,\n  label.padding = unit(0.3, \"lines\")\n) +\n  scale_x_continuous(breaks = breaks_pretty(), \n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"))+\n  theme_void()+\n  theme(\n    axis.text.x = element_text(),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\n# Plot age plot\nage_labels_plot <-\n  age_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text() +\n  theme_void()+\n  ggtitle(\"Age Group\\n(Years)\")+\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size=10,\n                                  face = \"bold\", color = \"black\"))\n# Combine everything (age + tw0 gender plots)\npopulation_pyramid_women +\n  age_labels_plot +\n  population_pyramid_men\n```\n:::\n\n#### Final Step: View the Population Pyramid Plot\n\nAfter layout adjustments, the population pyramid was plotted.\n\n::: panel-tabset\n## Population Pyramid\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n## Code for adjustments\n\n``` r\np6<-population_pyramid_women +\n  age_labels_plot +\n  population_pyramid_men +\n  plot_layout(\n    widths = c(4.3, 1, 4.3))+ # both sides are 4.3 times the age_label_plot\n  plot_annotation(\n    title = \"Age Pyramid of Singapore Resident Population for 2024\", \n    subtitle=\"(Population median age = 42)\",\n    caption = \"Data Source: Department of Statistics, Singapore | Designer: AT\",\n    theme = theme(plot.title = element_text(face = \"bold\", hjust = 0.20), \n                  plot.subtitle = element_text( hjust = 0.08),\n                  plot.background = element_rect(fill = \"#C1D3E5\"))\n)\nplot(p6)\n\ngrid.rect(\n  x = unit(0, \"npc\"),  \n  y = unit(1, \"npc\"),  \n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n:::\n\nThe population pyramid visualises the population's age and gender distribution. The population size is shown on the x-axis while the age-groups are represented on the middle y-axis. The population numbers are depicted within each age-group bar by gender on the left (Females) and right (Males). The bottom bar represents the youngest age group (0-4) and is incremental in age-group towards the top (90 & Over).\n\nIt is possible to visualise the regions within each age group as what [**Michal Palenik**](https://www.iz.sk/en/projects/eu-regions/AT) produced for three employment statuses. However, this method faces the issue of complexity and difficulty reading in our case due to having 5 regions, with the regions close in region size per age-group.\n\nSee an example below which visualises the complexity.\n\n### 7.1.1 Comparative Distribution and Structure of Age, Gender, and Population\n\n::: panel-tabset\n## Population Pyramid with Region\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n## Code for Population Pyramid with Region\n\n``` r\n# Order the data by Region_type within each Age and Gender group. \nsg_demo_2024_reshaped <- sg_demo_2024 %>%\n  arrange(Sex, Age_type, Region_type)\n\n# ordered factor\nsg_demo_2024_reshaped <- sg_demo_2024_reshaped %>%\n  mutate(Age_Type_Ordered2 = factor(Age_type, levels = age_labels$Age_type))\n\n# Create a basic bar chart for one gender\nbasic_plot <-  ggplot(sg_demo_2024_reshaped, \n                      aes(x = Age_Type_Ordered2, \n                          y= ifelse(Sex=='Females', -Pop, Pop), \n                          fill = Region_type)) + \ngeom_bar(stat = \"identity\") \n\n# Create population pyramids for both genders and combine them\npopulation_pyramid <- basic_plot +\n  coord_flip() +\n  theme_minimal() +\n  scale_fill_brewer(palette = \"Pastel2\") +\n  labs(\n    x = \"Age_type\",\n    y = \"Pop\",  \n    fill = \"Region_type\",  \n    title = \"Population Pyramid\")  +\n    scale_y_continuous(breaks = breaks_pretty(),\n                       labels = function(y) format(y, scientific = FALSE))+\n  geom_hline(yintercept = 0, color = \"blue\", linetype = \"dashed\", size = 0.5) + # Males and Females separation\n  annotate(geom = \"label\",x = 18, y = -100000,\n           label = \"Females\", fill = \"lightpink\",\n           color = \"black\",label.size = 0)+\n  annotate(geom = \"label\",x = 18, y = 100000,\n           label = \"Males\", fill = \"lightsteelblue\",\n           color = \"black\",label.size = 0)\nprint(population_pyramid) #  Display the plot\n```\n:::\n\n## 7.2 Histogram\n\n-   A histogram or density plot is usually used to visualise distributions. However, density plots assumes that each row of data is an independent observation of that variable. In our case, the Pop column was a summation instead of a single observation.\n\n-   Here, distribution of **Gender population by Age for Regions** is visualised.\n\n::: panel-tabset\n## The Histogram\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n## The Code for Histogram\n\n``` r\n# Using groupby() and summarise \npop_by_age_sex_region<- sg_demo_2024 %>%\n  group_by(Age_numerical, Sex, Region_type) %>%\n  summarize(pop_age = sum(Pop), .groups = \"drop\")\n\n# Sort ages\nsorted_ages2 <- sort(unique(pop_by_age_sex_region$Age_numerical))\n\n# Plot the age distribution using a histogram\np7<-ggplot(pop_by_age_sex_region, aes(x = Age_numerical, \n                                      y = pop_age, fill = Sex, \n                           text = paste(\"Age:\", Age_numerical, \"<br>\",\n                              \"Gender:\", Sex, \"<br>\",\n                              \"Population:\", scales::comma(pop_age)))) +\n  geom_bar(stat = \"identity\", color = \"black\", width = 1) +\n  scale_x_continuous(breaks = sorted_ages2,\n                     labels = sorted_ages2) +\n  labs(title = \"Gender population by Age for Regions\",\n       x = \"Age\",\n       y = \"Total Population\") +\n  scale_y_continuous(labels = scales::comma) +  \n  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=5, face = \"bold\"),\n        plot.title = element_text(hjust = 0.5, size = 11, face = \"bold\"),\n        axis.title.x = element_text(size = 8),\n        axis.title.y = element_text(size = 8),\n        axis.text.y = element_text(size = 8),\n        legend.title = element_text(size = 6),\n        legend.text = element_text(size = 6),\n        strip.text = element_text(size = 8))\n\np7\n```\n\n## Multiple Histograms\n\n\n::: {.cell}\n\n```{.r .cell-code}\np7+ facet_wrap(vars(Region_type), nrow=5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n:::\n\nThe histogram/ stacked bar chart shows the regional population distribution and regional gender distribution/ structure.\n\nThe charts above show `weighted_population` on the x-axis and `Region_type` or `Sex` on the y-axis. The `weighted_population` on the x-axis represents the total absolute population count for each specific combination of `Age_type`, `Region_type`, and `Sex`.\n\nThe y-axis of the `stat_halfeye()` component does NOT directly represent the population count, it represents the probability density of the `weighted_population` values within each level of the grouping variable on the y-axis (which is `Region_type` or `Sex)`.\n\nFor each gender and region:\n\n-   **Peaks:** Higher probability of age-gender combination in that region having a total population around the x-axis value.\n\n-   **Troughs:** Less common age-gender combination in that region having a total population around the x-axis value.\n\n-   **Spread:** The range of total populations across age categories within that region. A wider distribution indicates greater differences in population sizes between age groups.\n\n# 8. Daily Article\n\n::: centre\n![](/Aero_Media.png){fig-align=\"center\"}\n:::\n\n::: centre\n#### Singapore\n\n## **Demographic structures and distribution of Singapore in 2024**\n:::\n\n::: centre\n####### Author/ Graphical Editor: Audrey Tan\n\n####### Published Date: 03 May 2025\n:::\n\n##### In this article, we will cover population pyramids and pyramid graphs. These are useful to visualise the demographic structures and distributions of a country.\n\n## 8.1 Population Pyramid\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n**What is a population pyramid?**\n\nPopulation pyramids show the **age and gender population distribution**. It is useful for studying the effects of armed conflicts, mortality, birth policies and migration.\n\n**What are the types of population pyramid?**\n\nThere are three main types: Triangular shape (Expansive), Bell shape (Stationary), Bulb shape (Constrictive).\n\n::::: {.card .text-black .bg-light-purple .mb-3}\n::: {.card-header style=\"font-size: 1.5em; display: flex;\"}\n<img src=\"kitten_ball.png\" alt=\"Jedi Dog\" class=\"card-header-icon\" style=\"width: 70px; height: auto; vertical-align: middle; margin-right: 5px;\"/> **Insights**\n:::\n\n::: card-body\n#### **How about Singapore's population pyramid?** {.card-title}\n\n-   Singapore has a Constrictive type in year 2024. It is wider in the middle due to larger representation by the middle-age and elderly, but fewer young people. This is corroborated with the median age at 42.\n\n-   The top of the pyramid is wider than other two pyramid types, suggesting longer life expectancy.\n\n-   Females appears to outlive males as they aged, as seen from the longer bars. This difference is more prevalent for older age-groups (75s to more than 90s).\n\n-   This suggests an ageing population and low fertility.\n:::\n:::::\n\n## 8.2 Regional Distribution\n\n::: panel-tabset\n## Regional Population\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n## The Code for Regional Population\n\n``` r\n\n# Using groupby() and summarise \npop_by_sex<- sg_demo_2024 %>%\n  group_by(Sex, Region_type) %>%\n  summarize(pop_sex = sum(Pop), .groups = \"drop\")\n\n# Compute the position of labels\ndata <- pop_by_sex %>%\n  group_by(Region_type) %>% # Group by Region_type first\n  arrange(desc(Sex)) %>%\n  mutate(prop = pop_sex / sum(pop_sex) * 100) %>% # percentage within each region\n  mutate(ypos = cumsum(prop) - 0.5 * prop) #y-positions for labels within each region\n  \n# Calculate total population per region for ordering\nregion_order <- data %>%\n    group_by(Region_type) %>%\n    summarise(total_region_pop = sum(abs(pop_sex))) %>%\n    arrange(total_region_pop) %>%\n    pull(Region_type)\n\n# Order the Region_type factor\ndata$Region_type <- factor(data$Region_type, levels = region_order)\n\n# Plot\nggplot(data, aes(y = Region_type, fill = Sex)) +\n    geom_bar(data = subset(data, Sex == \"Males\"),\n             aes(x = pop_sex),\n             stat = \"identity\", fill = \"#00BFC4\",alpha = 0.8) +\n    geom_label(data = subset(data, Sex == \"Males\"),\n               aes(x = pop_sex,\n                   label = paste0(format(pop_sex, \n                                         scientific = FALSE, big.mark = \",\"))),\n                hjust = 0.5, nudge_x = -0.1 * max(abs(data$pop_sex)), \n               size = 3, color = \"black\", fill = \"grey90\") +\n    geom_bar(data = subset(data, Sex == \"Females\"),\n             aes(x = -pop_sex),\n             stat = \"identity\", fill = \"#F8766D\",alpha = 0.8) +\n    geom_label(data = subset(data, Sex == \"Females\"),\n               aes(x = -pop_sex,\n                   label = paste0(format(abs(pop_sex), \n                                         scientific = FALSE, big.mark = \",\"))),\n                hjust = 0.5, nudge_x = 0.1 * max(abs(data$pop_sex)), \n               size = 3, color = \"black\", fill = \"grey90\") +\nscale_x_continuous(\n    breaks = breaks_pretty(10),\n    labels = function(x) scales::comma(abs(x) / 1000, suffix = \"K\")\n)+\n    annotate(\n        geom = \"label\",\n        x = -max(abs(data$pop_sex)) * 1,\n        y = length(unique(data$Region_type)) + 0.8,\n        label = \"Females\",\n        fill = \"#F8766D\",\n        alpha = 0.8,\n        color = \"black\",\n        label.size = 0,\n        label.padding = unit(0.2, \"lines\"),\n        hjust=-0.8\n    )   +\n    annotate(\n        geom = \"label\",\n        x = max(abs(data$pop_sex)) * 1,\n        y = length(unique(data$Region_type)) + 0.8,\n        label = \"Males\",\n        fill = \"#00BFC4\",\n        alpha = 0.8,\n        color = \"black\",\n        label.size = 0,\n        label.padding = unit(0.2, \"lines\"),\n        hjust=2.5\n    ) +\n    scale_y_discrete(expand = expansion(mult = c(0, 0.3))) +\n    theme_bw() + # Using a clean theme\n    theme(axis.text = element_text(colour = \"black\"),\n          plot.title = element_text(lineheight = 0.8),\n          panel.grid.major.y = element_blank(), # Remove horizontal grid lines\n          panel.grid.minor = element_blank(),\n          legend.position = \"none\") +\n    labs(y = \"Region\", x = \"Population\", fill = \"Sex\")+\n  plot_annotation(title = \"Singapore Resident Population for 2024, by Region\",\n                  subtitle=\"Relative to other regions, the North-East Region is the region with the most residents, followed closely by the Central Region.\",\n                  caption = \"NER: North-East Region; CR: Central Region; WR: West Region; ER: East Region; NR: North Region\n\n. \\n Data Source: Department of Statistics, Singapore | Designer: AT\",\n                  theme = theme(plot.title = element_text(face = \"bold\", hjust = 0.16), \n                  plot.subtitle = element_text(size=8, hjust = 0.6),\n                  plot.background = element_rect(fill = \"#C1D3E5\"),\n                  plot.caption=element_text(size=8)))\n\ngrid.rect(\n  x = unit(0, \"npc\"),  \n  y = unit(1, \"npc\"),  \n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n:::\n\n::::: {.card .text-black .bg-light-purple .mb-3}\n::: {.card-header style=\"font-size: 1.5em; display: flex;\"}\n<img src=\"kitten_ball.png\" alt=\"Jedi Dog\" class=\"card-header-icon\" style=\"width: 70px; height: auto; vertical-align: middle; margin-right: 5px;\"/> **Insights**\n:::\n\n::: card-body\n#### **What is the regional-gender population distribution?** {.card-title}\n\n-   Most residents are clustered in NER, CR, and WR. A smaller segment in ER and NR.\n\n-   Closely even distribution of genders per region seen by colours and values.\n:::\n:::::\n\n*NER: North-East Region; CR: Central Region; WR: West Region; ER: East Region; NR: North Region*\n\n## 8.3 Region-Age-Gender Distribution\n\n::: panel-tabset\n## Code for the creation of age labels\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creation of age labels\nage_labels <-\n  tibble(\n    Age_type = c(\n      \"0-4\",\n      \"5-9\",\n      \"10-14\",\n      \"15-19\",\n      \"20-24\",\n      \"25-29\",\n      \"30-34\",\n      \"35-39\",\n      \"40-44\",\n      \"45-49\",\n      \"50-54\",\n      \"55-59\",\n      \"60-64\",\n      \"65-69\",\n      \"70-74\",\n      \"75-79\",\n      \"80-84\",\n      \"85-89\",\n      \"90 & Over\"\n    )\n  ) |>\n  mutate(\n    Age_type = fct_inorder(Age_type)\n  )\n```\n:::\n\n\n## Code for the creation of each region's dataframe\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(scales)\nlibrary(patchwork) # If you're combining the plots\n\n# Using groupby() and summarise \npop_ner <- pop_by_gender_age %>%\n  filter(Region_type == \"NER\") %>%\n  group_by(Sex, Age_Type_Ordered) %>%\n  summarize(pop_sex = sum(total_pop), .groups = \"drop\")\n\n# Using groupby() and summarise \npop_er <- pop_by_gender_age %>%\n  filter(Region_type == \"ER\") %>%\n  group_by(Sex, Age_Type_Ordered) %>%\n  summarize(pop_sex = sum(total_pop), .groups = \"drop\")\n\n# Using groupby() and summarise \npop_wr <- pop_by_gender_age %>%\n  filter(Region_type == \"WR\") %>%\n  group_by(Sex, Age_Type_Ordered) %>%\n  summarize(pop_sex = sum(total_pop), .groups = \"drop\")\n\n# Using groupby() and summarise \npop_cr <- pop_by_gender_age %>%\n  filter(Region_type == \"CR\") %>%\n  group_by(Sex, Age_Type_Ordered) %>%\n  summarize(pop_sex = sum(total_pop), .groups = \"drop\")\n\n# Using groupby() and summarise \npop_nr <- pop_by_gender_age %>%\n  filter(Region_type == \"NR\") %>%\n  group_by(Sex, Age_Type_Ordered) %>%\n  summarize(pop_sex = sum(total_pop), .groups = \"drop\")\n```\n:::\n\n\n## North Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Initial plot\npop_nr <-\n  pop_nr |>\n  mutate(pop_sex = if_else(Sex == \"Males\", pop_sex, -pop_sex))\n\n# One women plot\npopulation_pyramid_women <-\n  pop_nr |>\n  filter(Sex == \"Females\") |>\n  ggplot(aes(\n    x = -pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#F8766D\",alpha=0.8, width=0.7) +\n# Add Labelling  \n    geom_label(\n               aes(x = -pop_sex,\n                    label = paste0(format(pop_sex / 1000, \n                                          scientific = FALSE, digits = 2, trim = TRUE), \"K\")\n    ),\n                hjust = 0.8, nudge_x = -0.1 * max(abs(pop_nr$pop_sex)), \n               size = 2.6, color = \"black\", fill = \"grey90\") +\n# Annotations\n  annotate(\n    geom = \"label\",\n    x = -25000,\n    y = 19,\n    label = \"Females\",\n    fill = \"#F8766D\",\n    color = \"black\",\n    alpha=0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  ) +\n  scale_x_continuous(breaks = seq(-50000, 0, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(-50000,0) # Extend to the left for females\n  ) +\n  \n  theme_void()+\n  theme(\n    axis.text.x = element_text(size=8,margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\n\n# One men plot\npopulation_pyramid_men <-\n  pop_nr |>\n  filter(Sex == \"Males\") |>\n  ggplot(aes(\n    x = pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#00BFC4\",alpha=0.8, width=0.7)+\n  # Add Labelling  \n    geom_label(\n               aes(x = pop_sex,\n               label = paste0(format(pop_sex / 1000,\n                                      scientific = FALSE,\n                                      digits = 2,\n                                      trim = TRUE), \"K\")),\n    nudge_x = ifelse(subset(pop_nr, Sex == \"Males\")$Age_Type_Ordered %in% c(\"90 & Over\", \"85-89\"),\n                     0.15 * max(abs(pop_nr$pop_sex)), # those less than 1K \n                     0.15 * max(abs(pop_nr$pop_sex))), # others\n               size = 2.6, color = \"black\", fill = \"grey90\") +\n  #Annotations\n  annotate(\n    geom = \"label\",\n    x = 25000,\n    y = 19,\n    label = \"Males\",\n    fill = \"#00BFC4\",\n    alpha=0.8,\n    color = \"black\",\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  ) +\n  scale_x_continuous(breaks = seq(0, 50000, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(0, 50000) # Extend to the right for males\n  ) +\nscale_y_discrete()+\n  theme_void()+\n  theme(\n    axis.text.x = element_text(size=8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n    )\n  \n\n# Plot age plot\nage_labels_plot <-\n  age_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text(size=3) +\n  theme_void()+\n  ggtitle(\"Age Group\\n(Years)\")+\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size=6,\n                                  face = \"bold\", color = \"black\"))\n\n\np15<-population_pyramid_women +\n  age_labels_plot +\n  population_pyramid_men +\n  plot_layout(\n    widths = c(10, 1.8, 10))+ # both sides are x times the age_label_plot\n  plot_annotation(\n    title = \"Age Pyramid of Resident in North Region, 2024\", \n    subtitle=\"Within the region, large number of these residents are aged 25-64\",\n    caption = \"Data Source: Department of Statistics, Singapore | Designer: AT\",\n    theme = theme(plot.title = element_text(size=12, face = \"bold\", hjust = 0.1), \n                  plot.caption=element_text(size=5),\n                  plot.subtitle = element_text(hjust = 0.08),\n                  plot.background = element_rect(fill = \"#C1D3E5\"),\n                  plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), \"cm\")))\n\nplot(p15)\n\ngrid.rect(\n  x = unit(0, \"npc\"),  \n  y = unit(1, \"npc\"),  \n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n## East Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(grid)\n\n# --- Plot for East Region (pop_er) ---\n# Initial plot\npop_er <-\n  pop_er |>\n  mutate(pop_sex = if_else(Sex == \"Males\", pop_sex, -pop_sex))\n\npopulation_pyramid_women_er <-\n  pop_er |>\n  filter(Sex == \"Females\") |>\n  ggplot(aes(\n    x = -pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#F8766D\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = -pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    hjust = 0.7, nudge_x = -0.1 * max(abs(pop_er$pop_sex)),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = -25000,\n    y = 19,\n    label = \"Females\",\n    fill = \"#F8766D\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  )   +\n  scale_x_continuous(breaks = seq(-50000, 0, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(-50000,0) # Extend to the left for females\n  ) +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\npopulation_pyramid_men_er <-\n  pop_er |>\n  filter(Sex == \"Males\") |>\n  ggplot(aes(\n    x = pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#00BFC4\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    nudge_x = ifelse(subset(pop_er, Sex == \"Males\")$Age_Type_Ordered %in% c(\"90 & Over\", \"85-89\"),\n                     0.13 * max(abs(pop_er$pop_sex)),\n                     0.13 * max(abs(pop_er$pop_sex))),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = 25000,\n    y = 19,\n    label = \"Males\",\n    fill = \"#00BFC4\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  ) +\n  scale_x_continuous(breaks = seq(0, 50000, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(0, 50000) # Extend to the right for males\n  ) +\n  scale_y_discrete() +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\nage_labels_plot <- # Assuming this is already defined\n  age_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text(size = 3) +\n  theme_void() +\n  ggtitle(\"Age Group\\n(Years)\") +\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 6,\n                                  face = \"bold\", color = \"black\"))\n\np_er <- population_pyramid_women_er +\n  age_labels_plot +\n  population_pyramid_men_er +\n  plot_layout(\n    widths = c(10, 1.8, 10)) + # both sides are x times the age_label_plot\n  plot_annotation(\n    title = \"Age Pyramid of Resident in East Region, 2024\",\n    subtitle = \"Within the region, large number of these residents are aged 25-69\",\n    caption = \"Data Source: Department of Statistics, Singapore | Designer: AT\",\n    theme = theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.1),\n                  plot.caption = element_text(size = 5),\n                  plot.subtitle = element_text(hjust = 0.08),\n                  plot.background = element_rect(fill = \"#C1D3E5\"),\n                  plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), \"cm\")))\n\nplot(p_er)\n\ngrid.rect(\n  x = unit(0, \"npc\"),\n  y = unit(1, \"npc\"),\n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n## West Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Plot for West Region (pop_wr) ---\n# Initial plot\npop_wr <-\n  pop_wr |>\n  mutate(pop_sex = if_else(Sex == \"Males\", pop_sex, -pop_sex))\n\npopulation_pyramid_women_wr <-\n  pop_wr |>\n  filter(Sex == \"Females\") |>\n  ggplot(aes(\n    x = -pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#F8766D\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = -pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    hjust = 0.5, nudge_x = -0.1 * max(abs(pop_wr$pop_sex)),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = -25000,\n    y = 19,\n    label = \"Females\",\n    fill = \"#F8766D\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  )   +\n  scale_x_continuous(breaks = seq(-50000, 0, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(-50000,0) # Extend to the left for females\n  ) +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\npopulation_pyramid_men_wr <-\n  pop_wr |>\n  filter(Sex == \"Males\") |>\n  ggplot(aes(\n    x = pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#00BFC4\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    nudge_x = ifelse(subset(pop_wr, Sex == \"Males\")$Age_Type_Ordered %in% c(\"90 & Over\", \"85-89\"),\n                     0.11 * max(abs(pop_wr$pop_sex)),\n                     0.11 * max(abs(pop_wr$pop_sex))),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = 25000,\n    y = 19,\n    label = \"Males\",\n    fill = \"#00BFC4\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  ) +\n  scale_x_continuous(breaks = seq(0, 50000, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(0, 50000) # Extend to the right for males\n  ) +\n  scale_y_discrete() +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\nage_labels_plot <- # Assuming this is already defined\n  age_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text(size = 3) +\n  theme_void() +\n  ggtitle(\"Age Group\\n(Years)\") +\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 6,\n                                  face = \"bold\", color = \"black\"))\n\np_wr <- population_pyramid_women_wr +\n  age_labels_plot +\n  population_pyramid_men_wr +\n  plot_layout(\n    widths = c(10, 1.8, 10)) + # both sides are x times the age_label_plot\n  plot_annotation(\n    title = \"Age Pyramid of Resident in West Region, 2024\",\n    subtitle = \"Within the region, large number of these residents are aged 25-69\",\n    caption = \"Data Source: Department of Statistics, Singapore | Designer: AT\",\n    theme = theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.1),\n                  plot.caption = element_text(size = 5),\n                  plot.subtitle = element_text(hjust = 0.08),\n                  plot.background = element_rect(fill = \"#C1D3E5\"),\n                  plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), \"cm\")))\n\nplot(p_wr)\n\ngrid.rect(\n  x = unit(0, \"npc\"),\n  y = unit(1, \"npc\"),\n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n## Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Plot for Central Region (pop_cr) ---\n# Initial plot\npop_cr <-\n  pop_cr |>\n  mutate(pop_sex = if_else(Sex == \"Males\", pop_sex, -pop_sex))\n\n\npopulation_pyramid_women_cr <-\n  pop_cr |>\n  filter(Sex == \"Females\") |>\n  ggplot(aes(\n    x = -pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#F8766D\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = -pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    hjust = 0.5, nudge_x = -0.1 * max(abs(pop_cr$pop_sex)),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = -30000,\n    y = 19,\n    label = \"Females\",\n    fill = \"#F8766D\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  ) +\n  scale_x_continuous(breaks = breaks_pretty(4),\n                     labels = function(x) scales::comma(abs(x) / 1000, suffix = \"K\"),\n                     limits = c(-max(abs(pop_cr$pop_sex)) * 1.3, 0)) +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\npopulation_pyramid_men_cr <-\n  pop_cr |>\n  filter(Sex == \"Males\") |>\n  ggplot(aes(\n    x = pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#00BFC4\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    nudge_x = ifelse(subset(pop_cr, Sex == \"Males\")$Age_Type_Ordered %in% c(\"90 & Over\", \"85-89\"),\n                     0.09 * max(abs(pop_cr$pop_sex)),\n                     0.09 * max(abs(pop_cr$pop_sex))),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = 30000,\n    y = 19,\n    label = \"Males\",\n    fill = \"#00BFC4\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  ) +\n  scale_x_continuous(breaks = breaks_pretty(4),\n                     labels = function(x) scales::comma(abs(x) / 1000, suffix = \"K\"),\n                     limits = c(0, max(abs(pop_cr$pop_sex)) * 1.3)) +\n  scale_y_discrete() +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\nage_labels_plot <- # Assuming this is already defined\n  age_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text(size = 3) +\n  theme_void() +\n  ggtitle(\"Age Group\\n(Years)\") +\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 6,\n                                  face = \"bold\", color = \"black\"))\n\np_cr <- population_pyramid_women_cr +\n  age_labels_plot +\n  population_pyramid_men_cr +\n  plot_layout(\n    widths = c(10, 1.8, 10)) + # both sides are x times the age_label_plot\n  plot_annotation(\n    title = \"Age Pyramid of Resident in Central Region, 2024\",\n    subtitle = \"Within the region, large number of these residents are aged 30-69\",\n    caption = \"Data Source: Department of Statistics, Singapore | Designer: AT\",\n    theme = theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.1),\n                  plot.caption = element_text(size = 5),\n                  plot.subtitle = element_text(hjust = 0.08),\n                  plot.background = element_rect(fill = \"#C1D3E5\"),\n                  plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), \"cm\")))\n\nplot(p_cr)\n\ngrid.rect(\n  x = unit(0, \"npc\"),\n  y = unit(1, \"npc\"),\n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n## North East Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Plot for North East Region (pop_ner) ---\n# Initial plot\npop_ner <-\n  pop_ner |>\n  mutate(pop_sex = if_else(Sex == \"Males\", pop_sex, -pop_sex))\n\n\npopulation_pyramid_women_ner <-\n  pop_ner |>\n  filter(Sex == \"Females\") |>\n  ggplot(aes(\n    x = -pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#F8766D\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = -pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    hjust = 0.5, nudge_x = -0.1 * max(abs(pop_ner$pop_sex)),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = -30000,\n    y = 19,\n    label = \"Females\",\n    fill = \"#F8766D\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  )  +\n  scale_x_continuous(breaks = seq(-50000, 0, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(-50000,0) # Extend to the left for females\n  ) +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\npopulation_pyramid_men_ner <-\n  pop_ner |>\n  filter(Sex == \"Males\") |>\n  ggplot(aes(\n    x = pop_sex,\n    y = Age_Type_Ordered\n  )) +\n  geom_col(fill = \"#00BFC4\", alpha = 0.8, width = 0.7) +\n  geom_label(\n    aes(x = pop_sex,\n        label = paste0(format(pop_sex / 1000,\n                             scientific = FALSE, digits = 2, trim = TRUE), \"K\")),\n    nudge_x = ifelse(subset(pop_ner, Sex == \"Males\")$Age_Type_Ordered %in% c(\"90 & Over\", \"85-89\"),\n                     0.08 * max(abs(pop_ner$pop_sex)),\n                     0.08 * max(abs(pop_ner$pop_sex))),\n    size = 2.6, color = \"black\", fill = \"grey90\"\n  ) +\n  annotate(\n    geom = \"label\",\n    x = 30000,\n    y = 19,\n    label = \"Males\",\n    fill = \"#00BFC4\",\n    color = \"black\",\n    alpha = 0.8,\n    label.size = 0,\n    label.padding = unit(0.3, \"lines\")\n  )   +\n  scale_x_continuous(breaks = seq(0, 50000, by = 10000),\n                     labels=function(x) scales::comma(abs(x)/ 1000, suffix = \"K\"),\n    limits = c(0, 50000) # Extend to the right for males\n  ) +\n  scale_y_discrete() +\n  theme_void() +\n  theme(\n    axis.text.x = element_text(size = 8, margin = margin(t = 10)),\n    panel.grid.major.x = element_line(color = \"grey90\")\n  )\n\nage_labels_plot <- # Assuming this is already defined\n  age_labels |>\n  ggplot(\n    aes(\n      x = 1,\n      y = Age_type,\n      label = Age_type\n    )\n  ) +\n  geom_text(size = 3) +\n  theme_void() +\n  ggtitle(\"Age Group\\n(Years)\") +\n  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 6,\n                                  face = \"bold\", color = \"black\"))\n\np_ner <- population_pyramid_women_ner +\n  age_labels_plot +\n  population_pyramid_men_ner +\n  plot_layout(\n    widths = c(10, 1.8, 10)) + # both sides are x times the age_label_plot\n  plot_annotation(\n    title = \"Age Pyramid of Resident in North-East Region, 2024\",\n    subtitle = \"Within the region, large number of these residents are aged 30-69\",\n    caption = \"Data Source: Department of Statistics, Singapore | Designer: AT\",\n    theme = theme(plot.title = element_text(size = 12, face = \"bold\", hjust = 0.1),\n                  plot.caption = element_text(size = 5),\n                  plot.subtitle = element_text(hjust = 0.08),\n                  plot.background = element_rect(fill = \"#C1D3E5\"),\n                  plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), \"cm\")))\n\nplot(p_ner)\n\ngrid.rect(\n  x = unit(0, \"npc\"),\n  y = unit(1, \"npc\"),\n  width = unit(0.05, \"npc\"),\n  height = unit(0.025, \"npc\"),\n  just = c(\"left\", \"top\"),\n  gp = gpar(fill = \"#e5001c\", lwd = 0)\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n## The Final Combined Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Save the individual plots as image files\nggsave(\"p_nr.png\", p15, width = 8, height = 6, units = \"in\", dpi = 300)\nggsave(\"p_er.png\", p_er, width = 8, height = 6, units = \"in\", dpi = 300)\nggsave(\"p_wr.png\", p_wr, width = 8, height = 6, units = \"in\", dpi = 300)\nggsave(\"p_ner.png\", p_ner, width = 8, height = 6, units = \"in\", dpi = 300)\nggsave(\"p_cr.png\", p_cr, width = 8, height = 6, units = \"in\", dpi = 300)\n\n\n# 3. Read the image files using magick\nimage_nr <- image_read(\"p_nr.png\")\nimage_er <- image_read(\"p_er.png\")\nimage_wr <- image_read(\"p_wr.png\")\nimage_ner <- image_read(\"p_ner.png\")\nimage_cr <- image_read(\"p_cr.png\")\n\n\n# 4. Ensure consistent height and width for horizontal appending\ntarget_width = 10000\ntarget_height = 8000\nimage_nr <- image_scale(image_nr, geometry = paste0(target_width, \"x\", target_height))\nimage_er <- image_scale(image_er, geometry = paste0(target_width, \"x\", target_height))\nimage_wr <- image_scale(image_wr, geometry = paste0(target_width, \"x\", target_height))\nimage_ner <- image_scale(image_ner, geometry = paste0(target_width, \"x\", target_height))\nimage_cr <- image_scale(image_cr, geometry = paste0(target_width, \"x\", target_height))\n\n# 5. Create the rows\nrow1 <- image_append(c(image_nr, image_er), stack = FALSE)\nrow2 <- image_append(c(image_wr, image_ner), stack = FALSE)\nrow3 <- image_append(c(image_cr), stack = FALSE)\n\n\n# 6. Stack the rows vertically\ncombined_image <- image_append(c(row1, row2, row3), stack = TRUE)\n\n# 7. Add a main title\ncombined_image_with_title <- image_annotate(\n  combined_image,\n  \"Age Pyramids of Resident Population in Singapore Regions, 2024\",\n  size = 24,\n  color = \"black\",\n  boxcolor = \"white\",\n  font = \"sans\",\n  gravity = \"north\"\n)\n\n# 8. Save the combined image\nimage_write(combined_image_with_title, \"combined_pyramids_2x3.png\")\n\n# 9. Optionally display the combined image in R\nprint(combined_image_with_title)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  format width height colorspace matte filesize density\n  <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  \n1 PNG    20000  22500 sRGB       TRUE         0 118x118\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-41-1.png){width=10000}\n:::\n:::\n\n:::\n\n::::: {.card .text-black .bg-light-purple .mb-3}\n::: {.card-header style=\"font-size: 1.5em; display: flex;\"}\n<img src=\"kitten_ball.png\" alt=\"Jedi Dog\" class=\"card-header-icon\" style=\"width: 70px; height: auto; vertical-align: middle; margin-right: 5px;\"/> **Insights**\n:::\n\n::: card-body\n#### **Gender, Age and Regional Distributions** {.card-title}\n\n-   Wider distribution suggests greater diversity in the population per gender/ region:\n\n    -   Females have significantly wider distributions than Males for NER, CR, WR.\n\n    -   Regions NER, CR, WR have wider distributions than ER and NR.\n\n-   Across ages, wider gap between both genders' population count observed for NER, CR, and WR, compared to ER and NR.\n\n-   A rising trend from age 0- 35, plateauing around age 35- 60, then dips.\n\n-   Around the ages of 0- 30, the population values between genders are close.\n\n-   A large population around age 30- 60 suggests an older population.\n\n-   After age 75, a wider population gap is observed between the higher females compared to males. This is stark for \"over-90-years\" (especially for CR), suggesting longevity for older females.\n\n-   Distribution shape similar within (NER and CR), and (NR, ER, WR).\n:::\n:::::\n\n# 9. Summary and Future Research\n\n## 9.1 Summary\n\nBased on the EDA above, we can conclude the following about the demographic distribution and structure of Singapore in 2024:\n\n1.  **Age and Gender Distribution:** The population pyramid displays age-group variation in population. There is an ageing population with residents at a median age of 42. There are lesser younger and elderly from low birth rates and decline due to old-age mortality. There were increasingly more Females compared to Males as the age-group increases, suggesting Females outliving Males which corroborates with general biological and behavioural reasons.\n\n2.  **Age and Gender Distribution, for regions**: There is a rather even distribution of genders per region. Also, most residents are clustered in NER, CR and WR. Across different ages, a wider gap between the population count for both genders was observed for NER, CR, and WR as compared to ER and NR. Distribution shape similar within (NER and CR), and (NR, ER, WR).\n\n## 9.2 Future Research\n\n-   Further research can be done on the regions where the labour force (age 15 and over) reside in. This might be useful for urban planning of offices.\n\n-   With more data, labour force participation rate per region can be obtained by zooming into the working age groups (15-24, 25-54, 55-64, 65 and over).\n\n# 10. References and inspiration\n\n-   Steven P. Sanderson II, MPH (2023) [**Creating Population Pyramid Plots in R with ggplot2**](https://www.r-bloggers.com/2023/09/creating-population-pyramid-plots-in-r-with-ggplot2)\n\n-   David Keyes (2024) [**How to make polished population pyramids in ggplot: part 1**](https://rfortherestofus.com/2024/07/population-pyramid-part-1)\n\n-   Michal Palenik (2024) [**Deomographic Pyramid by Economic Activity Austria 2023**](https://www.iz.sk/en/projects/eu-regions/AT)\n\n-   Singstat (2024) [**Population Trends**](https://www.singstat.gov.sg/find-data/search-by-theme/population/geographic-distribution/latest-data)\n\n-   URA (2025) [**Regional Highlights**](https://www.ura.gov.sg/Corporate/Planning/Master-Plan/Master-Plan-2019/Regional-Highlights)\n\n-   National Geographic (2023) [**Population Pyramid**](https://education.nationalgeographic.org/resource/population-pyramid/)\n\n-   2travelacrosstime (2023) [**Types of Population Pyramids**](https://2travellingacrosstime.com/2023/08/19/types-of-population-pyramids/)\n\n-   Singapore Department of Statistics (2020) [**National Statistical Standards**](https://www.singstat.gov.sg/-/media/files/standards_and_classifications/nsa.ashx)\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}