project:
  type: website
  
website:
  title: "Covert Reef <img src='img/coral.png' style='height:1.2em; vertical-align:middle;'>"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: Take-home_Ex03.qmd
        text: Home
      - href: Introduction.qmd
        text: Introduction        
      - href: Storyboard_UI_Design.qmd
        text: Storyboard UI Design
      - href: r_packg.qmd
        text: Required R Packages   
      - href: Prototype.qmd
        text: Prototype in Netlify
      - href: shiny_under_construction.qmd
        text: Prototype translated to Shiny

format:
  html:
    theme: journal
    toc: true
    toc-depth: 2
    code-fold: true
    code-summary: "Show the code"
    css: ex03-style.css   
editor: visual
