---
title: "Take-home_Ex03"
author: "Audrey Tan"
date: "13 June 2025"
date-modified: "last-modified"
format:
  html:
    theme: journal          
    toc: true
    toc-depth: 2
    code-fold: true
    code-summary: "Show the code"
    page-layout: full
editor: visual
---

# **The Task for Take-Home Exercise 3**

In this take-home exercise, we are required to select one of the module of our proposed Shiny application and complete the following tasks:

-   To evaluate and determine the necessary R packages needed for our Shiny application are supported in R CRAN,

-   To prepare and test that the specific R codes can be run and return the correct output as expected,

-   To determine the parameters and outputs that will be exposed on the Shiny applications, and

-   To select the appropriate Shiny UI components for exposing the parameters determine above.

-   Include a storyboarding section called UI design for the different components of the UIs for the proposed design.

-   Prepare the prototype module report as Take-home Exercise 3 submission. The write-up of the take-home exercise must be in Quarto html document format and publish on Netlify on our own coursework page. The report must provide detail discussion and explanation of:

    -   the data preparation process;

    -   the selection of data visualisation techniques used; and

    -   the data visualisation design and interactivity principles and best practices implemented.
